-- https://www.complexsql.com/complex-sql-queries-examples-with-answers/
-- https://bytescout.com/blog/20-important-sql-queries.html
-- https://www.kaggle.com/learn/advanced-sql
-- https://www.sqlshack.com/learn-sql-how-to-write-a-complex-select-query/
-- https://www.khanacademy.org/computing/computer-programming/sql/more-advanced-sql-queries/pt/more-complex-queries-with-andor
-- https://www.lido.app/post/advanced-sql
-- https://learnsql.com/blog/advanced-sql-constructions-for-data-analyst/